### ISSUE TITLE
[Question] Where is %mycontainer_uri% used in the proxies defined

### ISSUE THREAD

**Issue by SteveALee** [joescars/TugOfWar-FunctionsDemo#3]
I cannot find `%mycontainer_uri%` either in the source, deployment (including in all Application Settings with kudo), in functions docs or indeed even with google?

What is it? MyGuess is in blob storage of some sort

thanks

**Comment by joescars** [comment]
Hi Steve, that is used for the "root" proxy to serve up the static content. You have to create a container named "content" and upload everything from the client folder to it. From there you use your blob container uri in that app settings. I am working on how to automate this piece. As of right now that is the only manual step.

**Comment by SteveALee** [comment]
Aha, thanks
Might be an idea to add to the README? 

I'm thinking of using a [c# function as a static server](http://anthonychu.ca/post/azure-functions-static-file-server/) for dev as that will give automatic Mime type handling. Though blob and CDN bette rfor deploy

**Comment by joescars** [comment]
I agree Steve. Going to add better instructions to the README shortly. In addition I'll update the azuredeploy to include the variable. 

I was going to use the function you referenced but wanted to keep this version completely node.js. I may do another version in c# for demo purposes using the static server.

**Comment by SteveALee** [comment]
I previously tried using connect in node and while you can do it by facading req and res I realised all files must be loaded into memory. 

Hopeully the JS AzureFunctions will support node streams soon.

**Comment by joescars** [comment]
@SteveALee  Updated the azuredeploy with the missing app settings. Updating the readme shortly as well. just FYI
